/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.awt.AWTUtilities;
import controlador.BienJpaController;
import controlador.Conexion;
import controlador.CuentaJpaController;
import controlador.DepartamentoJpaController;
import controlador.EmpleadoJpaController;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.image.RescaleOp;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import rojerusan.RSPanelsSlider;
import rojerusan.RSTableMetro;
import vista.Departamento;

/**
 *
 * @author Nahomi
 */
public class Principal extends javax.swing.JFrame {
    String ruta1 = System.getProperty("file.separator") + "src" +
        System.getProperty("file.separator") + "imagenes" +
        System.getProperty("file.separator") + "f1.jpg";
    String ruta2 = System.getProperty("file.separator") + "src" +
        System.getProperty("file.separator") + "imagenes" +
        System.getProperty("file.separator") + "blanco.jpg";
    private static Principal interfazPrincipal = null;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this,false); //hacemos el frame transparente
        transparencia(ruta1, 400,1000, 0.85f, minimenu);
        Border empty;
        empty = BorderFactory.createEmptyBorder(1, 1, 1, 1);
        final Border compound;
        Color crl = (new Color(255,255, 255));
        compound = BorderFactory.createCompoundBorder(empty, new redondear(crl));
        botones.setBorder(compound);
        //USAR PROXY POSTERIORMENTE
        DefaultComboBoxModel model = (DefaultComboBoxModel) cmbDep.getModel();
        model.removeAllElements();
        DepartamentoJpaController controladorDepartamento = new DepartamentoJpaController(Conexion.getInstancia().getEntityManager());
        List<vista.Departamento> arregloDepartamento = controladorDepartamento.findDepartamentoEntities();
        for(vista.Departamento departamento : arregloDepartamento)
        {
            model.addElement(departamento.getDescripcion());
        }
        model = (DefaultComboBoxModel) cmbCuenta.getModel();
        model.removeAllElements();
        CuentaJpaController controladorCuenta = new CuentaJpaController(Conexion.getInstancia().getEntityManager());
        List<vista.Cuenta> arregloCuenta = controladorCuenta.findCuentaEntities();
        for(vista.Cuenta cuenta : arregloCuenta)
        {
            model.addElement(cuenta.getNombre());
        }
    }
    
    public static Principal getInstancia()
    {
        if(interfazPrincipal == null) interfazPrincipal = new Principal();
        return interfazPrincipal;
    }
    private void transparencia(String ruta, int tamhorizontal, int tamvertical, float valor, JLabel label)
    {
        try
        {
            BufferedImage bim = ImageIO.read(new File(System.getProperty("user.dir") + ruta)); //creo un bufferimage con una imagen para el fondo
            BufferedImage nbim = new BufferedImage (tamhorizontal,tamvertical, BufferedImage.TYPE_4BYTE_ABGR_PRE); //creo otro bufferimage y le doy medidas, x, y y le doy el efecto de color que quiero
            Graphics2D createGraphics = nbim.createGraphics(); // creo una grafica a partir de la imagen
            createGraphics.drawImage(bim, null, 0, 0); //la dibujo
            float alp[] = new float[]{1f,1f,1f,valor}; // creo un vector con los valores para crear el efecto de transparencia
            float def [] = new float[]{0,0,0,0}; 
            RescaleOp r = new RescaleOp(alp, def, null);
            BufferedImage filter = r.filter(nbim, null); //creo un bufferimage con mi filtro y le mando la imagen que cree antes
            label.setIcon(new ImageIcon(filter)); 
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        botones = new javax.swing.JPanel();
        lbempleados1 = new javax.swing.JLabel();
        btnusuarios = new javax.swing.JButton();
        btnfinanciero = new javax.swing.JButton();
        btnmenuinventario = new javax.swing.JButton();
        btnmenuempleado = new javax.swing.JButton();
        lbfinanzas = new javax.swing.JLabel();
        lbempleados2 = new javax.swing.JLabel();
        lbempleados = new javax.swing.JLabel();
        btnguardar = new javax.swing.JLabel();
        pminimenu = new javax.swing.JPanel();
        rsminimenu = new rojerusan.RSPanelsSlider();
        pvacio = new javax.swing.JPanel();
        pempleado = new javax.swing.JPanel();
        btnnuevoempleado = new javax.swing.JButton();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        btnverempleados = new javax.swing.JButton();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        pinventario = new javax.swing.JPanel();
        btnnuevoarticulo = new javax.swing.JButton();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        btnverinventario = new javax.swing.JButton();
        rSMaterialButtonRectangle4 = new rojerusan.RSMaterialButtonRectangle();
        pFinanzas = new javax.swing.JPanel();
        btnEstadoR = new javax.swing.JButton();
        fondoEstadoR = new rojerusan.RSMaterialButtonRectangle();
        minimenu = new javax.swing.JLabel();
        ventana = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        rsmenu = new rojerusan.RSPanelsSlider();
        principal = new javax.swing.JPanel();
        jmpIngresarEmpleado = new jcMousePanel.jcMousePanel();
        lblingresarempleado = new javax.swing.JLabel();
        lblnombres = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        lbldpi = new javax.swing.JLabel();
        lblmunicipio = new javax.swing.JLabel();
        lbldepartamento = new javax.swing.JLabel();
        lbltipo = new javax.swing.JLabel();
        lblclasificacion = new javax.swing.JLabel();
        lbllugar = new javax.swing.JLabel();
        lblcargo = new javax.swing.JLabel();
        lblrenglonpre = new javax.swing.JLabel();
        lblprofesion = new javax.swing.JLabel();
        lblfechacontratacion = new javax.swing.JLabel();
        lblfechadesercion = new javax.swing.JLabel();
        lblsueldo = new javax.swing.JLabel();
        lblnoemergencia = new javax.swing.JLabel();
        txtnombreE = new javax.swing.JTextField();
        txtlugar = new javax.swing.JTextField();
        txtpuesto = new javax.swing.JTextField();
        txtcargo = new javax.swing.JTextField();
        txtdpi = new javax.swing.JTextField();
        txtsueldo = new javax.swing.JTextField();
        txttelE = new javax.swing.JTextField();
        txtapellidoE = new javax.swing.JTextField();
        txtmunicipio = new javax.swing.JTextField();
        cmbtipo = new javax.swing.JComboBox<>();
        cmbrenglonp = new javax.swing.JComboBox<>();
        cmbclasificacion = new javax.swing.JComboBox<>();
        cmbdepartamento = new javax.swing.JComboBox<>();
        rbtnOtroTipo = new javax.swing.JRadioButton();
        rbtnOtroClasificacion = new javax.swing.JRadioButton();
        fondonombre = new rojerusan.RSMaterialButtonRectangle();
        fondoapellido = new rojerusan.RSMaterialButtonRectangle();
        fondoDpi = new rojerusan.RSMaterialButtonRectangle();
        fondoMunicipio = new rojerusan.RSMaterialButtonRectangle();
        fondoDepartamento = new rojerusan.RSMaterialButtonRectangle();
        fondoTipo = new rojerusan.RSMaterialButtonRectangle();
        fondoclasificacion = new rojerusan.RSMaterialButtonRectangle();
        fondosueldo = new rojerusan.RSMaterialButtonRectangle();
        fondocargo = new rojerusan.RSMaterialButtonRectangle();
        fondorenglonp = new rojerusan.RSMaterialButtonRectangle();
        fondotelemergencia = new rojerusan.RSMaterialButtonRectangle();
        datefechadesercion = new rojeru_san.componentes.RSDateChooser();
        fondofechadesersion = new rojerusan.RSMaterialButtonRectangle();
        fondoprofesion = new rojerusan.RSMaterialButtonRectangle();
        fondolugar = new rojerusan.RSMaterialButtonRectangle();
        datefechacontratacion = new rojeru_san.componentes.RSDateChooser();
        fondofechacontratacion = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle5 = new rojerusan.RSMaterialButtonRectangle();
        jparticulo = new jcMousePanel.jcMousePanel();
        lblarticulo = new javax.swing.JLabel();
        lblcuenta = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        lbldescripcion = new javax.swing.JLabel();
        lbldepar = new javax.swing.JLabel();
        lbldonacion = new javax.swing.JLabel();
        lblfungible = new javax.swing.JLabel();
        lblcantidad = new javax.swing.JLabel();
        lblprecio = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtDes = new javax.swing.JTextArea();
        cmbDonado = new javax.swing.JComboBox<>();
        cmbDep = new javax.swing.JComboBox<>();
        cmbFungible = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        cmbCuenta = new javax.swing.JComboBox<>();
        fondodepart = new rojerusan.RSMaterialButtonRectangle();
        fondocuenta = new rojerusan.RSMaterialButtonRectangle();
        fondodescripcion = new rojerusan.RSMaterialButtonRectangle();
        fondocodigo = new rojerusan.RSMaterialButtonRectangle();
        fondodonacion = new rojerusan.RSMaterialButtonRectangle();
        fondofungible = new rojerusan.RSMaterialButtonRectangle();
        fondocantidad = new rojerusan.RSMaterialButtonRectangle();
        fondoprecio = new rojerusan.RSMaterialButtonRectangle();
        fondoestado = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle7 = new rojerusan.RSMaterialButtonRectangle();
        jmpEstadoR = new jcMousePanel.jcMousePanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblEstadoResultados = new rojerusan.RSTableMetro();
        fondoEstadoResultados = new rojerusan.RSMaterialButtonRectangle();
        jmpVerInventario = new jcMousePanel.jcMousePanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblInventario = new rojerusan.RSTableMetro();
        fondoVerInventario = new rojerusan.RSMaterialButtonRectangle();
        jmpVerEmpleado = new jcMousePanel.jcMousePanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblVerEmpleado = new rojerusan.RSTableMetro();
        fondoVerEmpleado = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N
        jcMousePanel1.setVisibleLogo(false);

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, -10, 280, 280));

        botones.setBackground(new java.awt.Color(204, 204, 255));
        botones.setOpaque(false);
        botones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbempleados1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lbempleados1.setText("  Usuarios");
        botones.add(lbempleados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 70, -1));

        btnusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-user-folder-50.png"))); // NOI18N
        btnusuarios.setToolTipText("usuarios");
        btnusuarios.setBorder(null);
        btnusuarios.setBorderPainted(false);
        btnusuarios.setContentAreaFilled(false);
        btnusuarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-user-folder-75.png"))); // NOI18N
        btnusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnusuariosMouseClicked(evt);
            }
        });
        botones.add(btnusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 90, 80));

        btnfinanciero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-receipt-and-change-50.png"))); // NOI18N
        btnfinanciero.setBorder(null);
        btnfinanciero.setBorderPainted(false);
        btnfinanciero.setContentAreaFilled(false);
        btnfinanciero.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-receipt-and-change-75.png"))); // NOI18N
        btnfinanciero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfinancieroMouseClicked(evt);
            }
        });
        botones.add(btnfinanciero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 90, 80));

        btnmenuinventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-in-inventory-50.png"))); // NOI18N
        btnmenuinventario.setBorder(null);
        btnmenuinventario.setBorderPainted(false);
        btnmenuinventario.setContentAreaFilled(false);
        btnmenuinventario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-in-inventory-75.png"))); // NOI18N
        btnmenuinventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmenuinventarioMouseClicked(evt);
            }
        });
        botones.add(btnmenuinventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 90, 80));

        btnmenuempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-team-50.png"))); // NOI18N
        btnmenuempleado.setBorder(null);
        btnmenuempleado.setBorderPainted(false);
        btnmenuempleado.setContentAreaFilled(false);
        btnmenuempleado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-team-75.png"))); // NOI18N
        btnmenuempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmenuempleadoMouseClicked(evt);
            }
        });
        botones.add(btnmenuempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 90, 80));

        lbfinanzas.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lbfinanzas.setText("  Finanzas  ");
        botones.add(lbfinanzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 90, -1));

        lbempleados2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lbempleados2.setText("  Inventario");
        botones.add(lbempleados2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 90, -1));

        lbempleados.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lbempleados.setText("  Empleados");
        botones.add(lbempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 90, -1));

        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnguardarMouseClicked(evt);
            }
        });
        botones.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 750));

        getContentPane().add(botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 90, 750));

        pminimenu.setBackground(new java.awt.Color(255, 255, 255));
        pminimenu.setOpaque(false);
        pminimenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rsminimenu.setOpaque(false);

        pvacio.setName("pvacio"); // NOI18N
        pvacio.setOpaque(false);

        javax.swing.GroupLayout pvacioLayout = new javax.swing.GroupLayout(pvacio);
        pvacio.setLayout(pvacioLayout);
        pvacioLayout.setHorizontalGroup(
            pvacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        pvacioLayout.setVerticalGroup(
            pvacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        rsminimenu.add(pvacio, "card2");

        pempleado.setName("pempleado"); // NOI18N
        pempleado.setOpaque(false);
        pempleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnnuevoempleado.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        btnnuevoempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-add-user-group-man-woman-45.png"))); // NOI18N
        btnnuevoempleado.setText("      Nuevo Empleado        ");
        btnnuevoempleado.setToolTipText("ingresar nuevo empleado");
        btnnuevoempleado.setActionCommand("   Nuevo Empleado   ");
        btnnuevoempleado.setBorder(null);
        btnnuevoempleado.setBorderPainted(false);
        btnnuevoempleado.setContentAreaFilled(false);
        btnnuevoempleado.setDefaultCapable(false);
        btnnuevoempleado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-add-user-group-man-woman-55.png"))); // NOI18N
        btnnuevoempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnuevoempleadoMouseClicked(evt);
            }
        });
        pempleado.add(btnnuevoempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 185, 270, 50));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle1.setText("fingresare");
        pempleado.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 290, 60));

        btnverempleados.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        btnverempleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-user-folder-45.png"))); // NOI18N
        btnverempleados.setText("  Empleados Contratados  ");
        btnverempleados.setToolTipText("ingresar nuevo empleado");
        btnverempleados.setBorder(null);
        btnverempleados.setBorderPainted(false);
        btnverempleados.setContentAreaFilled(false);
        btnverempleados.setDefaultCapable(false);
        btnverempleados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-user-folder-55.png"))); // NOI18N
        btnverempleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnverempleadosMouseClicked(evt);
            }
        });
        pempleado.add(btnverempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 256, 270, 50));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle2.setText("fingresare");
        pempleado.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 290, 60));

        rsminimenu.add(pempleado, "card3");

        pinventario.setName("pinventario"); // NOI18N
        pinventario.setOpaque(false);
        pinventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnnuevoarticulo.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        btnnuevoarticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-add-list-45.png"))); // NOI18N
        btnnuevoarticulo.setText("      Nuevo Articulo        ");
        btnnuevoarticulo.setToolTipText("ingresar nuevo articulo");
        btnnuevoarticulo.setActionCommand("   Nuevo Empleado   ");
        btnnuevoarticulo.setBorder(null);
        btnnuevoarticulo.setBorderPainted(false);
        btnnuevoarticulo.setContentAreaFilled(false);
        btnnuevoarticulo.setDefaultCapable(false);
        btnnuevoarticulo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-add-list-55.png"))); // NOI18N
        btnnuevoarticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnuevoarticuloMouseClicked(evt);
            }
        });
        pinventario.add(btnnuevoarticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 185, 270, 50));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle3.setText("fingresare");
        pinventario.add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 290, 60));

        btnverinventario.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        btnverinventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-list-view-45.png"))); // NOI18N
        btnverinventario.setText("         Inventario            ");
        btnverinventario.setToolTipText("ver Inventario");
        btnverinventario.setBorder(null);
        btnverinventario.setBorderPainted(false);
        btnverinventario.setContentAreaFilled(false);
        btnverinventario.setDefaultCapable(false);
        btnverinventario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-list-view-55.png"))); // NOI18N
        btnverinventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnverinventarioMouseClicked(evt);
            }
        });
        pinventario.add(btnverinventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 256, 270, 50));

        rSMaterialButtonRectangle4.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle4.setText("fingresare");
        pinventario.add(rSMaterialButtonRectangle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 290, 60));

        rsminimenu.add(pinventario, "card3");

        pFinanzas.setName("pFinanzas"); // NOI18N
        pFinanzas.setOpaque(false);
        pFinanzas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEstadoR.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        btnEstadoR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-add-list-45.png"))); // NOI18N
        btnEstadoR.setText("    Estado de Resultados      ");
        btnEstadoR.setToolTipText("ingresar nuevo articulo");
        btnEstadoR.setActionCommand("   Nuevo Empleado   ");
        btnEstadoR.setBorder(null);
        btnEstadoR.setBorderPainted(false);
        btnEstadoR.setContentAreaFilled(false);
        btnEstadoR.setDefaultCapable(false);
        btnEstadoR.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-add-list-55.png"))); // NOI18N
        btnEstadoR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEstadoRMouseClicked(evt);
            }
        });
        pFinanzas.add(btnEstadoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 185, 270, 50));

        fondoEstadoR.setBackground(new java.awt.Color(255, 255, 255));
        fondoEstadoR.setText("fingresare");
        pFinanzas.add(fondoEstadoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 290, 60));

        rsminimenu.add(pFinanzas, "card5");

        pminimenu.add(rsminimenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 750));
        pminimenu.add(minimenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 750));

        getContentPane().add(pminimenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 330, 750));

        ventana.setBackground(new java.awt.Color(255, 255, 255));
        ventana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-cancel-45.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        ventana.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, 52));

        principal.setBackground(new java.awt.Color(255, 255, 255));
        principal.setName("principal"); // NOI18N
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        rsmenu.add(principal, "card3");

        jmpIngresarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fmenu4.png"))); // NOI18N
        jmpIngresarEmpleado.setName("jpmIngresarEmpleado"); // NOI18N
        jmpIngresarEmpleado.setVisibleLogo(false);
        jmpIngresarEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblingresarempleado.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 48)); // NOI18N
        lblingresarempleado.setForeground(new java.awt.Color(255, 255, 255));
        lblingresarempleado.setText("Ingresar Empleado");
        jmpIngresarEmpleado.add(lblingresarempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 28, 470, 70));

        lblnombres.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblnombres.setText("Nombres:");
        jmpIngresarEmpleado.add(lblnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, 30));

        lblapellido.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblapellido.setText("Apellidos:");
        jmpIngresarEmpleado.add(lblapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 150, 30));

        lbldpi.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lbldpi.setText("DPI:");
        jmpIngresarEmpleado.add(lbldpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 120, 30));

        lblmunicipio.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblmunicipio.setText("Municipio:");
        jmpIngresarEmpleado.add(lblmunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 130, 30));

        lbldepartamento.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lbldepartamento.setText("Departamento:");
        jmpIngresarEmpleado.add(lbldepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 190, 30));

        lbltipo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lbltipo.setText("Tipo:");
        jmpIngresarEmpleado.add(lbltipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 80, 30));

        lblclasificacion.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblclasificacion.setText("Clasificación:");
        jmpIngresarEmpleado.add(lblclasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 160, 30));

        lbllugar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lbllugar.setText("Lugar:");
        jmpIngresarEmpleado.add(lbllugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 90, 30));

        lblcargo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblcargo.setText("Cargo:");
        jmpIngresarEmpleado.add(lblcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 150, 30));

        lblrenglonpre.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblrenglonpre.setText("Renglón presupuestario:");
        jmpIngresarEmpleado.add(lblrenglonpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 290, 30));

        lblprofesion.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblprofesion.setText("Profesión:");
        jmpIngresarEmpleado.add(lblprofesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 290, 30));

        lblfechacontratacion.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblfechacontratacion.setText("Fecha de contraración:");
        jmpIngresarEmpleado.add(lblfechacontratacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 330, 30));

        lblfechadesercion.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblfechadesercion.setText("Fecha de deserción:");
        jmpIngresarEmpleado.add(lblfechadesercion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 330, 30));

        lblsueldo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblsueldo.setText("Sueldo:");
        jmpIngresarEmpleado.add(lblsueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 90, 30));

        lblnoemergencia.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblnoemergencia.setText("Emergencia(tel):");
        jmpIngresarEmpleado.add(lblnoemergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 200, 30));

        txtnombreE.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtnombreE.setBorder(null);
        jmpIngresarEmpleado.add(txtnombreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 300, 30));

        txtlugar.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtlugar.setBorder(null);
        jmpIngresarEmpleado.add(txtlugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 330, 30));

        txtpuesto.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtpuesto.setBorder(null);
        jmpIngresarEmpleado.add(txtpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 380, 30));

        txtcargo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtcargo.setBorder(null);
        jmpIngresarEmpleado.add(txtcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 300, 30));

        txtdpi.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtdpi.setBorder(null);
        jmpIngresarEmpleado.add(txtdpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 300, 30));

        txtsueldo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtsueldo.setBorder(null);
        jmpIngresarEmpleado.add(txtsueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 280, 30));

        txttelE.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txttelE.setBorder(null);
        jmpIngresarEmpleado.add(txttelE, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, 180, 30));

        txtapellidoE.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtapellidoE.setBorder(null);
        jmpIngresarEmpleado.add(txtapellidoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 300, 30));

        txtmunicipio.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtmunicipio.setBorder(null);
        jmpIngresarEmpleado.add(txtmunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 300, 30));

        cmbtipo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        cmbtipo.setForeground(new java.awt.Color(0, 52, 102));
        cmbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro de Salud", "Puesto de Salud", "Racana", "Territorio I", "Territorio II", "Territorio III", "Territorio IV", "Territorio V", "Territorio VI", "Territorio VII" }));
        cmbtipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbtipoItemStateChanged(evt);
            }
        });
        jmpIngresarEmpleado.add(cmbtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 270, -1));

        cmbrenglonp.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        cmbrenglonp.setForeground(new java.awt.Color(0, 52, 102));
        cmbrenglonp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "011", "182", "189", "029", "036" }));
        jmpIngresarEmpleado.add(cmbrenglonp, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 100, 30));

        cmbclasificacion.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        cmbclasificacion.setForeground(new java.awt.Color(0, 52, 102));
        cmbclasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una clasificación", "Tipo A", "Tipo B" }));
        jmpIngresarEmpleado.add(cmbclasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 180, 30));

        cmbdepartamento.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        cmbdepartamento.setForeground(new java.awt.Color(0, 52, 102));
        cmbdepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Totonicapán", "Quetzaltenango", "Guatemala", "Izabal", "Petén", "Huehuetenango", "Quiché", "Alta Verapaz", "San Marcos", "Sololá", "Chimaltenango", "Sacatepéquez", "Baja Verapaz", "El Progreso", "Jalapa", "Zacapa", "Chiquimula", "Retalhuleu", "Suchitepéquez", "Escuintla", "Santa Rosa", "Jutiapa" }));
        jmpIngresarEmpleado.add(cmbdepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 410, -1));

        rbtnOtroTipo.setBackground(new java.awt.Color(255, 255, 255));
        rbtnOtroTipo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        rbtnOtroTipo.setText("Otro");
        jmpIngresarEmpleado.add(rbtnOtroTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, -1));

        rbtnOtroClasificacion.setBackground(new java.awt.Color(255, 255, 255));
        rbtnOtroClasificacion.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        rbtnOtroClasificacion.setText("Otro");
        jmpIngresarEmpleado.add(rbtnOtroClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, -1, 30));

        fondonombre.setBackground(new java.awt.Color(186, 240, 255));
        fondonombre.setEnabled(false);
        jmpIngresarEmpleado.add(fondonombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 320, 50));

        fondoapellido.setBackground(new java.awt.Color(186, 240, 255));
        fondoapellido.setEnabled(false);
        jmpIngresarEmpleado.add(fondoapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 320, 50));

        fondoDpi.setBackground(new java.awt.Color(186, 240, 255));
        fondoDpi.setEnabled(false);
        jmpIngresarEmpleado.add(fondoDpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 320, 50));

        fondoMunicipio.setBackground(new java.awt.Color(186, 240, 255));
        fondoMunicipio.setEnabled(false);
        jmpIngresarEmpleado.add(fondoMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 320, 50));

        fondoDepartamento.setBackground(new java.awt.Color(186, 240, 255));
        fondoDepartamento.setEnabled(false);
        jmpIngresarEmpleado.add(fondoDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 430, 50));

        fondoTipo.setBackground(new java.awt.Color(186, 240, 255));
        fondoTipo.setEnabled(false);
        jmpIngresarEmpleado.add(fondoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 290, 50));

        fondoclasificacion.setBackground(new java.awt.Color(186, 240, 255));
        jmpIngresarEmpleado.add(fondoclasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 200, 50));

        fondosueldo.setBackground(new java.awt.Color(186, 240, 255));
        fondosueldo.setEnabled(false);
        jmpIngresarEmpleado.add(fondosueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, 300, 50));

        fondocargo.setBackground(new java.awt.Color(186, 240, 255));
        fondocargo.setEnabled(false);
        jmpIngresarEmpleado.add(fondocargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 320, 50));

        fondorenglonp.setBackground(new java.awt.Color(186, 240, 255));
        fondorenglonp.setEnabled(false);
        jmpIngresarEmpleado.add(fondorenglonp, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, 120, 50));

        fondotelemergencia.setBackground(new java.awt.Color(186, 240, 255));
        fondotelemergencia.setEnabled(false);
        jmpIngresarEmpleado.add(fondotelemergencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 550, 200, 50));

        datefechadesercion.setEnabled(false);
        datefechadesercion.setName("datefechadesercion"); // NOI18N
        jmpIngresarEmpleado.add(datefechadesercion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 380, -1));

        fondofechadesersion.setBackground(new java.awt.Color(186, 240, 255));
        fondofechadesersion.setEnabled(false);
        fondofechadesersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fondofechadesersionActionPerformed(evt);
            }
        });
        jmpIngresarEmpleado.add(fondofechadesersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 400, 50));

        fondoprofesion.setBackground(new java.awt.Color(186, 240, 255));
        fondoprofesion.setEnabled(false);
        jmpIngresarEmpleado.add(fondoprofesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 400, 50));

        fondolugar.setBackground(new java.awt.Color(186, 240, 255));
        fondolugar.setEnabled(false);
        jmpIngresarEmpleado.add(fondolugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 350, 50));

        datefechacontratacion.setName("datefechacontratacion"); // NOI18N
        jmpIngresarEmpleado.add(datefechacontratacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 380, -1));

        fondofechacontratacion.setBackground(new java.awt.Color(186, 240, 255));
        fondofechacontratacion.setEnabled(false);
        jmpIngresarEmpleado.add(fondofechacontratacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 400, 50));

        rSMaterialButtonRectangle5.setBackground(new java.awt.Color(0, 3, 102));
        rSMaterialButtonRectangle5.setText("Ingresar empleado");
        rSMaterialButtonRectangle5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonRectangle5MouseClicked(evt);
            }
        });
        jmpIngresarEmpleado.add(rSMaterialButtonRectangle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 630, 210, -1));

        rsmenu.add(jmpIngresarEmpleado, "card7");

        jparticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fmenu4.png"))); // NOI18N
        jparticulo.setName("jparticulo"); // NOI18N
        jparticulo.setVisibleLogo(false);
        jparticulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblarticulo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 48)); // NOI18N
        lblarticulo.setForeground(new java.awt.Color(255, 255, 255));
        lblarticulo.setText("Ingresar artículo");
        jparticulo.add(lblarticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 28, 470, 70));

        lblcuenta.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblcuenta.setText("Cuenta:");
        jparticulo.add(lblcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 190, 40));

        lblcodigo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblcodigo.setText("Código:");
        jparticulo.add(lblcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 150, 40));

        lbldescripcion.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lbldescripcion.setText("Descripción:");
        jparticulo.add(lbldescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 150, 40));

        lbldepar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lbldepar.setText("Departamento:");
        jparticulo.add(lbldepar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 190, 40));

        lbldonacion.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lbldonacion.setText("Donación:");
        jparticulo.add(lbldonacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 190, 40));

        lblfungible.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblfungible.setText("Fungible:");
        jparticulo.add(lblfungible, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 190, 40));

        lblcantidad.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblcantidad.setText("Cantidad:");
        jparticulo.add(lblcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 190, 40));

        lblprecio.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblprecio.setText("Precio:");
        jparticulo.add(lblprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 190, 40));

        lblestado.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        lblestado.setText("Estado:");
        jparticulo.add(lblestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 190, 40));

        txtPrecio.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtPrecio.setBorder(null);
        jparticulo.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 220, 40));

        txtCodigo.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtCodigo.setBorder(null);
        jparticulo.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 280, 40));

        txtCantidad.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtCantidad.setBorder(null);
        jparticulo.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 220, 40));

        txtDes.setColumns(20);
        txtDes.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        txtDes.setRows(5);
        txtDes.setBorder(null);
        jparticulo.add(txtDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 410, 110));

        cmbDonado.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        cmbDonado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        jparticulo.add(cmbDonado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 230, 40));

        cmbDep.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jparticulo.add(cmbDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 410, 30));

        cmbFungible.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        cmbFungible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        jparticulo.add(cmbFungible, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 230, 40));

        cmbEstado.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Malo" }));
        jparticulo.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 220, 40));

        cmbCuenta.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        jparticulo.add(cmbCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 400, 220, 40));

        fondodepart.setBackground(new java.awt.Color(186, 240, 255));
        fondodepart.setEnabled(false);
        jparticulo.add(fondodepart, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 430, 50));

        fondocuenta.setBackground(new java.awt.Color(186, 240, 255));
        fondocuenta.setEnabled(false);
        jparticulo.add(fondocuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 240, 60));

        fondodescripcion.setBackground(new java.awt.Color(186, 240, 255));
        fondodescripcion.setEnabled(false);
        jparticulo.add(fondodescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 430, 130));

        fondocodigo.setBackground(new java.awt.Color(186, 240, 255));
        fondocodigo.setEnabled(false);
        jparticulo.add(fondocodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 300, 60));

        fondodonacion.setBackground(new java.awt.Color(186, 240, 255));
        fondodonacion.setEnabled(false);
        jparticulo.add(fondodonacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 250, 60));

        fondofungible.setBackground(new java.awt.Color(186, 240, 255));
        fondofungible.setEnabled(false);
        jparticulo.add(fondofungible, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 250, 60));

        fondocantidad.setBackground(new java.awt.Color(186, 240, 255));
        fondocantidad.setEnabled(false);
        jparticulo.add(fondocantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 240, 60));

        fondoprecio.setBackground(new java.awt.Color(186, 240, 255));
        fondoprecio.setEnabled(false);
        jparticulo.add(fondoprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 240, 60));

        fondoestado.setBackground(new java.awt.Color(186, 240, 255));
        fondoestado.setEnabled(false);
        jparticulo.add(fondoestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 240, 60));

        rSMaterialButtonRectangle7.setBackground(new java.awt.Color(0, 54, 102));
        rSMaterialButtonRectangle7.setText("Guardar");
        rSMaterialButtonRectangle7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSMaterialButtonRectangle7MouseClicked(evt);
            }
        });
        jparticulo.add(rSMaterialButtonRectangle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, -1, -1));

        rsmenu.add(jparticulo, "card5");

        jmpEstadoR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fmenu4.png"))); // NOI18N
        jmpEstadoR.setName("jmpEstadoR"); // NOI18N
        jmpEstadoR.setVisibleLogo(false);
        jmpEstadoR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEstadoResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cantidad", "Descrpción", "Debe", "Haber", "Código"
            }
        ));
        tblEstadoResultados.setColorBackgoundHead(new java.awt.Color(0, 54, 102));
        tblEstadoResultados.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblEstadoResultados.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblEstadoResultados.setColorFilasForeground1(new java.awt.Color(0, 54, 102));
        tblEstadoResultados.setColorFilasForeground2(new java.awt.Color(0, 54, 102));
        tblEstadoResultados.setColorSelBackgound(new java.awt.Color(0, 54, 102));
        jScrollPane3.setViewportView(tblEstadoResultados);
        if (tblEstadoResultados.getColumnModel().getColumnCount() > 0) {
            tblEstadoResultados.getColumnModel().getColumn(4).setHeaderValue("Código");
        }

        jmpEstadoR.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 930, 470));

        fondoEstadoResultados.setBackground(new java.awt.Color(186, 240, 255));
        fondoEstadoResultados.setEnabled(false);
        jmpEstadoR.add(fondoEstadoResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 970, 510));

        rsmenu.add(jmpEstadoR, "card7");

        jmpVerInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fmenu4.png"))); // NOI18N
        jmpVerInventario.setName("jmpVerInventario"); // NOI18N
        jmpVerInventario.setVisibleLogo(false);
        jmpVerInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrpción", "Cantidad", "Precio Unitario", "Estado", "Fungible", "Total"
            }
        ));
        tblInventario.setColorBackgoundHead(new java.awt.Color(0, 54, 102));
        tblInventario.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblInventario.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblInventario.setColorFilasForeground1(new java.awt.Color(0, 54, 102));
        tblInventario.setColorFilasForeground2(new java.awt.Color(0, 54, 102));
        tblInventario.setColorSelBackgound(new java.awt.Color(0, 54, 102));
        jScrollPane4.setViewportView(tblInventario);
        if (tblInventario.getColumnModel().getColumnCount() > 0) {
            tblInventario.getColumnModel().getColumn(4).setHeaderValue("Código");
        }

        jmpVerInventario.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 930, 470));

        fondoVerInventario.setBackground(new java.awt.Color(186, 240, 255));
        fondoVerInventario.setEnabled(false);
        jmpVerInventario.add(fondoVerInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 970, 510));

        rsmenu.add(jmpVerInventario, "card7");

        jmpVerEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fmenu4.png"))); // NOI18N
        jmpVerEmpleado.setName("jmpVerEmpleado"); // NOI18N
        jmpVerEmpleado.setVisibleLogo(false);
        jmpVerEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVerEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Lugar", "Profesión"
            }
        ));
        tblVerEmpleado.setColorBackgoundHead(new java.awt.Color(0, 54, 102));
        tblVerEmpleado.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tblVerEmpleado.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblVerEmpleado.setColorFilasForeground1(new java.awt.Color(0, 54, 102));
        tblVerEmpleado.setColorFilasForeground2(new java.awt.Color(0, 54, 102));
        tblVerEmpleado.setColorSelBackgound(new java.awt.Color(0, 54, 102));
        jScrollPane5.setViewportView(tblVerEmpleado);

        jmpVerEmpleado.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 930, 470));

        fondoVerEmpleado.setBackground(new java.awt.Color(186, 240, 255));
        fondoVerEmpleado.setEnabled(false);
        jmpVerEmpleado.add(fondoVerEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 970, 510));

        rsmenu.add(jmpVerEmpleado, "card7");

        ventana.add(rsmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 750));

        getContentPane().add(ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 1010, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseClicked

    }//GEN-LAST:event_btnguardarMouseClicked

    private void btnnuevoempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnuevoempleadoMouseClicked
        rsmenu.setPanelSlider((int) 1.2,jmpIngresarEmpleado, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnnuevoempleadoMouseClicked

    private void btnmenuempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuempleadoMouseClicked
        rsminimenu.setPanelSlider((int)1.2,pempleado, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnmenuempleadoMouseClicked

    private void cmbtipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbtipoItemStateChanged

    }//GEN-LAST:event_cmbtipoItemStateChanged

    private void btnverempleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnverempleadosMouseClicked
        rsmenu.setPanelSlider((int)1.2,jmpVerEmpleado, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnverempleadosMouseClicked

    private void btnmenuinventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuinventarioMouseClicked
       rsminimenu.setPanelSlider((int)1.2,pinventario, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnmenuinventarioMouseClicked

    private void btnnuevoarticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnuevoarticuloMouseClicked
        rsmenu.setPanelSlider((int)1.2,jparticulo, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnnuevoarticuloMouseClicked

    private void btnverinventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnverinventarioMouseClicked
        rsmenu.setPanelSlider((int)1.2,jmpVerInventario, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnverinventarioMouseClicked

    private void btnfinancieroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfinancieroMouseClicked
        rsminimenu.setPanelSlider((int)1.2,pFinanzas, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnfinancieroMouseClicked

    private void btnusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusuariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnusuariosMouseClicked

    private void fondofechadesersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fondofechadesersionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fondofechadesersionActionPerformed

    private void btnEstadoRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstadoRMouseClicked
        rsmenu.setPanelSlider((int)1.2,jmpEstadoR, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnEstadoRMouseClicked

    private void rSMaterialButtonRectangle7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle7MouseClicked
        /**
         * INGRESO DE ARTÍCULOS
         * se ordenaran los datos del formulario para ingresarlos a la base de datos
         */
        BienJpaController controladorBien = new BienJpaController(Conexion.getInstancia().getEntityManager());
        DepartamentoJpaController controladorDepartamento = new DepartamentoJpaController((Conexion.getInstancia().getEntityManager()));
        CuentaJpaController controladorCuenta = new CuentaJpaController(Conexion.getInstancia().getEntityManager());
        vista.Bien bien = new vista.Bien();
        bien.setCodigo(txtCodigo.getText());
        bien.setDescripcion(txtDes.getText());
        bien.setDepartamentoId(controladorDepartamento.findeDepartamento(cmbDep.getSelectedItem().toString()));
        if(cmbDonado.getSelectedIndex() == 0) bien.setDonado((short) 1); //Sí es donado
        else bien.setDonado((short) 0); //No es donado
        if(cmbFungible.getSelectedIndex() == 0) bien.setFungible((short) 1);//Sí es fungible
        else bien.setFungible((short) 0); //No es fungible
        int cantidad = Integer.parseInt(txtCantidad.getText());
        double precio = Double.parseDouble(txtPrecio.getText());
        double precioTotal = cantidad*precio;
        bien.setCantidad(cantidad);
        bien.setPrecioUnitario(precio);
        bien.setPrecioTotal(precioTotal);
        if(cmbEstado.getSelectedIndex() == 0) bien.setEstado((short) 1); //Está en buen estado
        else bien.setEstado((short) 0); //Está en mal estado
        bien.setCuentaId(controladorCuenta.findCuenta(cmbCuenta.getSelectedItem().toString()));
        controladorBien.create(bien);
        JOptionPane.showMessageDialog(null, "Bien ingresado");
    }//GEN-LAST:event_rSMaterialButtonRectangle7MouseClicked

    private void rSMaterialButtonRectangle5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle5MouseClicked
        /**
         * INGRESO DE EMPLEADOS
         * Se ordenan los datos del formulario para ingresarlos a la base de datos
         */
        EmpleadoJpaController controladorEmpleado = new EmpleadoJpaController(Conexion.getInstancia().getEntityManager());
        vista.Empleado empleado = new vista.Empleado();
        empleado.setNombres(txtnombreE.getText());
        empleado.setApellidos(txtapellidoE.getText());
        empleado.setDpi(txtdpi.getText());
        empleado.setMunicipio(txtmunicipio.getText().toLowerCase());
        empleado.setDepartamento(cmbdepartamento.getSelectedItem().toString());
        if(rbtnOtroTipo.isSelected()) empleado.setTipo("otro"); //si otro tipo es seleccionado
        else empleado.setTipo(cmbtipo.getSelectedItem().toString());
        if(rbtnOtroClasificacion.isSelected()) empleado.setClasificacion("otro"); //si otra clasificación es seleccionada
        else empleado.setTipo(cmbclasificacion.getSelectedItem().toString());
        empleado.setLugar(txtlugar.getText());
        empleado.setCargo(txtcargo.getText());
        empleado.setRenglonPresupuestario(cmbrenglonp.getSelectedItem().toString());
        empleado.setPuesto(txtpuesto.getText());
        empleado.setFechaInicio(datefechacontratacion.getDatoFecha());
        empleado.setSueldo(Double.parseDouble(txtsueldo.getText()));
        empleado.setTelefono(txttelE.getText());
        controladorEmpleado.create(empleado);
        JOptionPane.showMessageDialog(this, "Empleado ingresado");
    }//GEN-LAST:event_rSMaterialButtonRectangle5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botones;
    private javax.swing.JButton btnEstadoR;
    public javax.swing.JButton btnfinanciero;
    private javax.swing.JLabel btnguardar;
    public javax.swing.JButton btnmenuempleado;
    public javax.swing.JButton btnmenuinventario;
    private javax.swing.JButton btnnuevoarticulo;
    private javax.swing.JButton btnnuevoempleado;
    public javax.swing.JButton btnusuarios;
    private javax.swing.JButton btnverempleados;
    private javax.swing.JButton btnverinventario;
    private javax.swing.JComboBox<String> cmbCuenta;
    private javax.swing.JComboBox<String> cmbDep;
    private javax.swing.JComboBox<String> cmbDonado;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbFungible;
    private javax.swing.JComboBox<String> cmbclasificacion;
    private javax.swing.JComboBox<String> cmbdepartamento;
    private javax.swing.JComboBox<String> cmbrenglonp;
    private javax.swing.JComboBox<String> cmbtipo;
    private rojeru_san.componentes.RSDateChooser datefechacontratacion;
    private rojeru_san.componentes.RSDateChooser datefechadesercion;
    private rojerusan.RSMaterialButtonRectangle fondoDepartamento;
    private rojerusan.RSMaterialButtonRectangle fondoDpi;
    private rojerusan.RSMaterialButtonRectangle fondoEstadoR;
    private rojerusan.RSMaterialButtonRectangle fondoEstadoResultados;
    private rojerusan.RSMaterialButtonRectangle fondoMunicipio;
    private rojerusan.RSMaterialButtonRectangle fondoTipo;
    private rojerusan.RSMaterialButtonRectangle fondoVerEmpleado;
    private rojerusan.RSMaterialButtonRectangle fondoVerInventario;
    private rojerusan.RSMaterialButtonRectangle fondoapellido;
    private rojerusan.RSMaterialButtonRectangle fondocantidad;
    private rojerusan.RSMaterialButtonRectangle fondocargo;
    private rojerusan.RSMaterialButtonRectangle fondoclasificacion;
    private rojerusan.RSMaterialButtonRectangle fondocodigo;
    private rojerusan.RSMaterialButtonRectangle fondocuenta;
    private rojerusan.RSMaterialButtonRectangle fondodepart;
    private rojerusan.RSMaterialButtonRectangle fondodescripcion;
    private rojerusan.RSMaterialButtonRectangle fondodonacion;
    private rojerusan.RSMaterialButtonRectangle fondoestado;
    private rojerusan.RSMaterialButtonRectangle fondofechacontratacion;
    private rojerusan.RSMaterialButtonRectangle fondofechadesersion;
    private rojerusan.RSMaterialButtonRectangle fondofungible;
    private rojerusan.RSMaterialButtonRectangle fondolugar;
    private rojerusan.RSMaterialButtonRectangle fondonombre;
    private rojerusan.RSMaterialButtonRectangle fondoprecio;
    private rojerusan.RSMaterialButtonRectangle fondoprofesion;
    private rojerusan.RSMaterialButtonRectangle fondorenglonp;
    private rojerusan.RSMaterialButtonRectangle fondosueldo;
    private rojerusan.RSMaterialButtonRectangle fondotelemergencia;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private jcMousePanel.jcMousePanel jmpEstadoR;
    private jcMousePanel.jcMousePanel jmpIngresarEmpleado;
    private jcMousePanel.jcMousePanel jmpVerEmpleado;
    private jcMousePanel.jcMousePanel jmpVerInventario;
    private jcMousePanel.jcMousePanel jparticulo;
    private javax.swing.JLabel lbempleados;
    private javax.swing.JLabel lbempleados1;
    private javax.swing.JLabel lbempleados2;
    private javax.swing.JLabel lbfinanzas;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblarticulo;
    private javax.swing.JLabel lblcantidad;
    private javax.swing.JLabel lblcargo;
    private javax.swing.JLabel lblclasificacion;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lblcuenta;
    private javax.swing.JLabel lbldepar;
    private javax.swing.JLabel lbldepartamento;
    private javax.swing.JLabel lbldescripcion;
    private javax.swing.JLabel lbldonacion;
    private javax.swing.JLabel lbldpi;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblfechacontratacion;
    private javax.swing.JLabel lblfechadesercion;
    private javax.swing.JLabel lblfungible;
    private javax.swing.JLabel lblingresarempleado;
    private javax.swing.JLabel lbllugar;
    private javax.swing.JLabel lblmunicipio;
    private javax.swing.JLabel lblnoemergencia;
    private javax.swing.JLabel lblnombres;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JLabel lblprofesion;
    private javax.swing.JLabel lblrenglonpre;
    private javax.swing.JLabel lblsueldo;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JLabel minimenu;
    private javax.swing.JPanel pFinanzas;
    private javax.swing.JPanel pempleado;
    private javax.swing.JPanel pinventario;
    private javax.swing.JPanel pminimenu;
    private javax.swing.JPanel principal;
    private javax.swing.JPanel pvacio;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle4;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle5;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle7;
    private javax.swing.JRadioButton rbtnOtroClasificacion;
    private javax.swing.JRadioButton rbtnOtroTipo;
    private rojerusan.RSPanelsSlider rsmenu;
    private rojerusan.RSPanelsSlider rsminimenu;
    private rojerusan.RSTableMetro tblEstadoResultados;
    private rojerusan.RSTableMetro tblInventario;
    private rojerusan.RSTableMetro tblVerEmpleado;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDes;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtapellidoE;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtdpi;
    private javax.swing.JTextField txtlugar;
    private javax.swing.JTextField txtmunicipio;
    private javax.swing.JTextField txtnombreE;
    private javax.swing.JTextField txtpuesto;
    private javax.swing.JTextField txtsueldo;
    private javax.swing.JTextField txttelE;
    private javax.swing.JPanel ventana;
    // End of variables declaration//GEN-END:variables
}