/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.awt.AWTUtilities;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.awt.image.RescaleOp;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import rojerusan.RSPanelsSlider;
import rojerusan.RSTableMetro;

/**
 *
 * @author Nahomi
 */
public class principal extends javax.swing.JFrame {
String ruta1 = "/src/imagenes/f3.jpg";
String ruta2 = "/src/imagenes/blanco.jpg";
    /**
     * Creates new form Principal
     */
    public principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        AWTUtilities.setWindowOpaque(this,false); //hacemos el frame transparente
        transparencia(ruta1, 400,1000, 0.55f, minimenu);
        transparencia(ruta2, 100, 1000, 0.55f, lbbotones);
    }
    private void transparencia(String ruta, int tamhorizontal, int tamvertical, float valor, JLabel label)
    {
        try
        {
            BufferedImage bim = ImageIO.read(new File(System.getProperty("user.dir") + ruta)); //creo un bufferimage con una imagen para el fondo
            BufferedImage nbim = new BufferedImage (tamhorizontal,tamvertical, BufferedImage.TYPE_4BYTE_ABGR_PRE); //creo otro bufferimage y le doy medidas, x, y y le doy el efecto de color que quiero
            Graphics2D createGraphics = nbim.createGraphics(); // creo una grafica a partir de la imagen
            createGraphics.drawImage(bim, null, 0, 0); //la dibujo
            float alp[] = new float[]{1f,1f,1f,valor}; // creo un vector con los valores para crear el efecto de transparencia
            float def [] = new float[]{0,0,0,0}; 
            RescaleOp r = new RescaleOp(alp, def, null);
            BufferedImage filter = r.filter(nbim, null); //creo un bufferimage con mi filtro y le mando la imagen que cree antes
            label.setIcon(new ImageIcon(filter)); 
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        botones = new javax.swing.JPanel();
        lbempleados1 = new javax.swing.JLabel();
        btnusuarios = new javax.swing.JButton();
        btnfinanciero = new javax.swing.JButton();
        btnmenuinventario = new javax.swing.JButton();
        btnmenuempleado = new javax.swing.JButton();
        lbfinanzas = new javax.swing.JLabel();
        lbempleados2 = new javax.swing.JLabel();
        lbempleados = new javax.swing.JLabel();
        lbbotones = new javax.swing.JLabel();
        pminimenu = new javax.swing.JPanel();
        rsminimenu = new rojerusan.RSPanelsSlider();
        pvacio = new javax.swing.JPanel();
        pempleado = new javax.swing.JPanel();
        btnnuevoempleado = new javax.swing.JButton();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        btnverempleados = new javax.swing.JButton();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        pinventario = new javax.swing.JPanel();
        btnnuevoarticulo = new javax.swing.JButton();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        btnverinventario = new javax.swing.JButton();
        rSMaterialButtonRectangle4 = new rojerusan.RSMaterialButtonRectangle();
        minimenu = new javax.swing.JLabel();
        ventana = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        rsmenu = new rojerusan.RSPanelsSlider();
        principal = new javax.swing.JPanel();
        pingresarE = new javax.swing.JPanel();
        cmbtipo = new javax.swing.JComboBox<>();
        txtnombreE = new javax.swing.JTextField();
        rSMaterialButtonRectangle5 = new rojerusan.RSMaterialButtonRectangle();
        cmbrenglonp = new javax.swing.JComboBox<>();
        txtpuesto = new javax.swing.JTextField();
        cmblugar = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtdpi = new javax.swing.JTextField();
        rSMaterialButtonRectangle29 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle27 = new rojerusan.RSMaterialButtonRectangle();
        jRadioButton4 = new javax.swing.JRadioButton();
        rSMaterialButtonRectangle23 = new rojerusan.RSMaterialButtonRectangle();
        jLabel38 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        rSMaterialButtonRectangle19 = new rojerusan.RSMaterialButtonRectangle();
        txtcargo = new javax.swing.JTextField();
        txtsueldo = new javax.swing.JTextField();
        cmbclasificacion = new javax.swing.JComboBox<>();
        rSMaterialButtonRectangle25 = new rojerusan.RSMaterialButtonRectangle();
        txttelE = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtapellidoE = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        rSMaterialButtonRectangle26 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle17 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle28 = new rojerusan.RSMaterialButtonRectangle();
        jLabel40 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        cmbdepartamento = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        rSMaterialButtonRectangle6 = new rojerusan.RSMaterialButtonRectangle();
        jLabel46 = new javax.swing.JLabel();
        txtmunicipio = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        rSMaterialButtonRectangle22 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle24 = new rojerusan.RSMaterialButtonRectangle();
        jLabel35 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        rSMaterialButtonRectangle20 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle21 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle18 = new rojerusan.RSMaterialButtonRectangle();
        jLabel23 = new javax.swing.JLabel();
        pverEmpleado = new javax.swing.JPanel();
        rSMaterialButtonRectangle30 = new rojerusan.RSMaterialButtonRectangle();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo1.png"))); // NOI18N

        javax.swing.GroupLayout jcMousePanel1Layout = new javax.swing.GroupLayout(jcMousePanel1);
        jcMousePanel1.setLayout(jcMousePanel1Layout);
        jcMousePanel1Layout.setHorizontalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jcMousePanel1Layout.setVerticalGroup(
            jcMousePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jcMousePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, -15, 280, 280));

        botones.setBackground(new java.awt.Color(204, 204, 255));
        botones.setOpaque(false);
        botones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbempleados1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lbempleados1.setText("  Usuarios");
        botones.add(lbempleados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 70, -1));

        btnusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-user-folder-50.png"))); // NOI18N
        btnusuarios.setToolTipText("usuarios");
        btnusuarios.setBorder(null);
        btnusuarios.setBorderPainted(false);
        btnusuarios.setContentAreaFilled(false);
        btnusuarios.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-user-folder-75.png"))); // NOI18N
        btnusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnusuariosMouseClicked(evt);
            }
        });
        botones.add(btnusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 90, 80));

        btnfinanciero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-receipt-and-change-50.png"))); // NOI18N
        btnfinanciero.setBorder(null);
        btnfinanciero.setBorderPainted(false);
        btnfinanciero.setContentAreaFilled(false);
        btnfinanciero.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-receipt-and-change-75.png"))); // NOI18N
        btnfinanciero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnfinancieroMouseClicked(evt);
            }
        });
        botones.add(btnfinanciero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 90, 80));

        btnmenuinventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-in-inventory-50.png"))); // NOI18N
        btnmenuinventario.setBorder(null);
        btnmenuinventario.setBorderPainted(false);
        btnmenuinventario.setContentAreaFilled(false);
        btnmenuinventario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-in-inventory-75.png"))); // NOI18N
        btnmenuinventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmenuinventarioMouseClicked(evt);
            }
        });
        botones.add(btnmenuinventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 90, 80));

        btnmenuempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-team-50.png"))); // NOI18N
        btnmenuempleado.setBorder(null);
        btnmenuempleado.setBorderPainted(false);
        btnmenuempleado.setContentAreaFilled(false);
        btnmenuempleado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-team-75.png"))); // NOI18N
        btnmenuempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmenuempleadoMouseClicked(evt);
            }
        });
        botones.add(btnmenuempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 90, 80));

        lbfinanzas.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lbfinanzas.setText("  Finanzas  ");
        botones.add(lbfinanzas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 70, -1));

        lbempleados2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lbempleados2.setText("  Inventario");
        botones.add(lbempleados2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 70, -1));

        lbempleados.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lbempleados.setText("  Empleados");
        botones.add(lbempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 70, -1));

        lbbotones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbbotonesMouseClicked(evt);
            }
        });
        botones.add(lbbotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 750));

        getContentPane().add(botones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 90, 750));

        pminimenu.setBackground(new java.awt.Color(255, 255, 255));
        pminimenu.setOpaque(false);
        pminimenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rsminimenu.setOpaque(false);

        pvacio.setName("pvacio"); // NOI18N
        pvacio.setOpaque(false);

        javax.swing.GroupLayout pvacioLayout = new javax.swing.GroupLayout(pvacio);
        pvacio.setLayout(pvacioLayout);
        pvacioLayout.setHorizontalGroup(
            pvacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        pvacioLayout.setVerticalGroup(
            pvacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        rsminimenu.add(pvacio, "card2");

        pempleado.setName("pempleado"); // NOI18N
        pempleado.setOpaque(false);
        pempleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnnuevoempleado.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        btnnuevoempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-add-user-group-man-woman-45.png"))); // NOI18N
        btnnuevoempleado.setText("      Nuevo Empleado        ");
        btnnuevoempleado.setToolTipText("ingresar nuevo empleado");
        btnnuevoempleado.setActionCommand("   Nuevo Empleado   ");
        btnnuevoempleado.setBorder(null);
        btnnuevoempleado.setBorderPainted(false);
        btnnuevoempleado.setContentAreaFilled(false);
        btnnuevoempleado.setDefaultCapable(false);
        btnnuevoempleado.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-add-user-group-man-woman-55.png"))); // NOI18N
        btnnuevoempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnuevoempleadoMouseClicked(evt);
            }
        });
        pempleado.add(btnnuevoempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 185, 270, 50));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle1.setText("fingresare");
        pempleado.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 290, 60));

        btnverempleados.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        btnverempleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-user-folder-45.png"))); // NOI18N
        btnverempleados.setText("  Empleados Contratados  ");
        btnverempleados.setToolTipText("ingresar nuevo empleado");
        btnverempleados.setBorder(null);
        btnverempleados.setBorderPainted(false);
        btnverempleados.setContentAreaFilled(false);
        btnverempleados.setDefaultCapable(false);
        btnverempleados.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-user-folder-55.png"))); // NOI18N
        btnverempleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnverempleadosMouseClicked(evt);
            }
        });
        pempleado.add(btnverempleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 256, 270, 50));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle2.setText("fingresare");
        pempleado.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 290, 60));

        rsminimenu.add(pempleado, "card3");

        pinventario.setName("pinventario"); // NOI18N
        pinventario.setOpaque(false);
        pinventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnnuevoarticulo.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        btnnuevoarticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-add-list-45.png"))); // NOI18N
        btnnuevoarticulo.setText("      Nuevo Articulo        ");
        btnnuevoarticulo.setToolTipText("ingresar nuevo articulo");
        btnnuevoarticulo.setActionCommand("   Nuevo Empleado   ");
        btnnuevoarticulo.setBorder(null);
        btnnuevoarticulo.setBorderPainted(false);
        btnnuevoarticulo.setContentAreaFilled(false);
        btnnuevoarticulo.setDefaultCapable(false);
        btnnuevoarticulo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-add-list-55.png"))); // NOI18N
        btnnuevoarticulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnnuevoarticuloMouseClicked(evt);
            }
        });
        pinventario.add(btnnuevoarticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 185, 270, 50));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle3.setText("fingresare");
        pinventario.add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 290, 60));

        btnverinventario.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        btnverinventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-list-view-45.png"))); // NOI18N
        btnverinventario.setText("         Inventario            ");
        btnverinventario.setToolTipText("ver Inventario");
        btnverinventario.setBorder(null);
        btnverinventario.setBorderPainted(false);
        btnverinventario.setContentAreaFilled(false);
        btnverinventario.setDefaultCapable(false);
        btnverinventario.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-list-view-55.png"))); // NOI18N
        btnverinventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnverinventarioMouseClicked(evt);
            }
        });
        pinventario.add(btnverinventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 256, 270, 50));

        rSMaterialButtonRectangle4.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle4.setText("fingresare");
        pinventario.add(rSMaterialButtonRectangle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 290, 60));

        rsminimenu.add(pinventario, "card3");

        pminimenu.add(rsminimenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 750));
        pminimenu.add(minimenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 750));

        getContentPane().add(pminimenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 330, 750));

        ventana.setBackground(new java.awt.Color(255, 255, 255));
        ventana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8-cancel-45.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        ventana.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, 52));

        principal.setBackground(new java.awt.Color(255, 255, 255));
        principal.setName("principal"); // NOI18N
        principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        rsmenu.add(principal, "card3");

        pingresarE.setBackground(new java.awt.Color(255, 255, 255));
        pingresarE.setName("pingresarE"); // NOI18N
        pingresarE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbtipo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        cmbtipo.setForeground(new java.awt.Color(0, 52, 102));
        cmbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centro de Salud", "Puesto de Salud", "Racana", "Territorio I", "Territorio II", "Territorio III", "Territorio IV", "Territorio V", "Territorio VI", "Territorio VII" }));
        cmbtipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbtipoItemStateChanged(evt);
            }
        });
        pingresarE.add(cmbtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 270, -1));

        txtnombreE.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtnombreE.setBorder(null);
        pingresarE.add(txtnombreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 300, 30));

        rSMaterialButtonRectangle5.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle5.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 320, 50));

        cmbrenglonp.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        cmbrenglonp.setForeground(new java.awt.Color(0, 52, 102));
        cmbrenglonp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "011", "182", "189", "029", "036" }));
        pingresarE.add(cmbrenglonp, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 100, 30));

        txtpuesto.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtpuesto.setBorder(null);
        pingresarE.add(txtpuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 380, 30));

        cmblugar.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        cmblugar.setBorder(null);
        cmblugar.setEnabled(false);
        pingresarE.add(cmblugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 330, 30));

        jLabel32.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel32.setText("Municipio:");
        pingresarE.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 130, 30));

        txtdpi.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtdpi.setBorder(null);
        pingresarE.add(txtdpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 300, 30));

        rSMaterialButtonRectangle29.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle29.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle29, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 320, 50));

        rSMaterialButtonRectangle27.setBackground(new java.awt.Color(186, 240, 255));
        pingresarE.add(rSMaterialButtonRectangle27, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 200, 50));

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jRadioButton4.setText("Otro");
        pingresarE.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

        rSMaterialButtonRectangle23.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle23.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle23, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, 300, 50));

        jLabel38.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel38.setText("Emergencia(tel):");
        pingresarE.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 590, 200, 30));

        jLabel41.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel41.setText("Renglón presupuestario:");
        pingresarE.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 290, 30));

        rSMaterialButtonRectangle19.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle19.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle19, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 290, 50));

        txtcargo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtcargo.setBorder(null);
        pingresarE.add(txtcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, 300, 30));

        txtsueldo.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtsueldo.setBorder(null);
        pingresarE.add(txtsueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 280, 30));

        cmbclasificacion.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        cmbclasificacion.setForeground(new java.awt.Color(0, 52, 102));
        cmbclasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una clasificación", "Tipo A", "Tipo B" }));
        pingresarE.add(cmbclasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 530, 180, 30));

        rSMaterialButtonRectangle25.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle25.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle25, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 320, 50));

        txttelE.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txttelE.setBorder(null);
        pingresarE.add(txttelE, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 180, 30));

        jLabel37.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel37.setText("Fecha de deserción:");
        pingresarE.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 330, 30));

        txtapellidoE.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtapellidoE.setBorder(null);
        pingresarE.add(txtapellidoE, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 300, 30));

        jLabel42.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel42.setText("DPI:");
        pingresarE.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 120, 30));

        rSMaterialButtonRectangle26.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle26.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle26, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, 120, 50));

        rSMaterialButtonRectangle17.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle17.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 320, 50));

        rSMaterialButtonRectangle28.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle28.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle28, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 200, 50));

        jLabel40.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel40.setText("Profesión:");
        pingresarE.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 290, 30));

        jLabel39.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel39.setText("Fecha de contraración:");
        pingresarE.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 330, 30));

        jLabel33.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel33.setText("Departamento:");
        pingresarE.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 190, 30));

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jRadioButton3.setText("Otro");
        pingresarE.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, -1, 30));

        cmbdepartamento.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        cmbdepartamento.setForeground(new java.awt.Color(0, 52, 102));
        cmbdepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Totonicapán", "Quetzaltenango", "Guatemala", "Izabal", "Petén", "Huehuetenango", "Quiché", "Alta Verapaz", "San Marcos", "Sololá", "Chimaltenango", "Sacatepéquez", "Baja Verapaz", "El Progreso", "Jalapa", "Zacapa", "Chiquimula", "Retalhuleu", "Suchitepéquez", "Escuintla", "Santa Rosa", "Jutiapa" }));
        pingresarE.add(cmbdepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 410, -1));

        jLabel34.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel34.setText("Tipo:");
        pingresarE.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 80, 30));

        rSMaterialButtonRectangle6.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle6.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 320, 50));

        jLabel46.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel46.setText("Sueldo:");
        pingresarE.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 90, 30));

        txtmunicipio.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txtmunicipio.setBorder(null);
        pingresarE.add(txtmunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 300, 30));

        jLabel45.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel45.setText("Cargo:");
        pingresarE.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 150, 30));

        jLabel36.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel36.setText("Lugar:");
        pingresarE.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 590, 90, 30));

        rSMaterialButtonRectangle22.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle22.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 400, 50));

        rSMaterialButtonRectangle24.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle24.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 400, 50));

        jLabel35.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel35.setText("Clasificación:");
        pingresarE.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 160, 30));

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel20.setText("Nombres:");
        pingresarE.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 150, 30));

        rSMaterialButtonRectangle20.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle20.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 350, 50));

        rSMaterialButtonRectangle21.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle21.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 400, 50));

        rSMaterialButtonRectangle18.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle18.setEnabled(false);
        pingresarE.add(rSMaterialButtonRectangle18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 430, 50));

        jLabel23.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel23.setText("Apellidos:");
        pingresarE.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 150, 30));

        rsmenu.add(pingresarE, "card2");

        pverEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        pverEmpleado.setName("pverEmpleado"); // NOI18N
        pverEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSMaterialButtonRectangle30.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle30.setEnabled(false);
        pverEmpleado.add(rSMaterialButtonRectangle30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 970, 510));

        rsmenu.add(pverEmpleado, "card4");

        ventana.add(rsmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 750));

        getContentPane().add(ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 1010, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

    private void lbbotonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbotonesMouseClicked

    }//GEN-LAST:event_lbbotonesMouseClicked

    private void btnnuevoempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnuevoempleadoMouseClicked
        rsmenu.setPanelSlider((int) 1.2, pingresarE, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnnuevoempleadoMouseClicked

    private void btnmenuempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuempleadoMouseClicked
        rsminimenu.setPanelSlider((int)1.2,pempleado, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnmenuempleadoMouseClicked

    private void cmbtipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbtipoItemStateChanged

    }//GEN-LAST:event_cmbtipoItemStateChanged

    private void btnverempleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnverempleadosMouseClicked
        rsmenu.setPanelSlider((int)1.2,pverEmpleado, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnverempleadosMouseClicked

    private void btnmenuinventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuinventarioMouseClicked
       rsminimenu.setPanelSlider((int)1.2,pinventario, RSPanelsSlider.DIRECT.UP);
    }//GEN-LAST:event_btnmenuinventarioMouseClicked

    private void btnnuevoarticuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnnuevoarticuloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnuevoarticuloMouseClicked

    private void btnverinventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnverinventarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnverinventarioMouseClicked

    private void btnfinancieroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfinancieroMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfinancieroMouseClicked

    private void btnusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusuariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnusuariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botones;
    private javax.swing.JButton btnfinanciero;
    private javax.swing.JButton btnmenuempleado;
    private javax.swing.JButton btnmenuinventario;
    private javax.swing.JButton btnnuevoarticulo;
    private javax.swing.JButton btnnuevoempleado;
    private javax.swing.JButton btnusuarios;
    private javax.swing.JButton btnverempleados;
    private javax.swing.JButton btnverinventario;
    private javax.swing.JComboBox<String> cmbclasificacion;
    private javax.swing.JComboBox<String> cmbdepartamento;
    private javax.swing.JTextField cmblugar;
    private javax.swing.JComboBox<String> cmbrenglonp;
    private javax.swing.JComboBox<String> cmbtipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JLabel lbbotones;
    private javax.swing.JLabel lbempleados;
    private javax.swing.JLabel lbempleados1;
    private javax.swing.JLabel lbempleados2;
    private javax.swing.JLabel lbfinanzas;
    private javax.swing.JLabel minimenu;
    private javax.swing.JPanel pempleado;
    private javax.swing.JPanel pingresarE;
    private javax.swing.JPanel pinventario;
    private javax.swing.JPanel pminimenu;
    private javax.swing.JPanel principal;
    private javax.swing.JPanel pvacio;
    private javax.swing.JPanel pverEmpleado;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle17;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle18;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle19;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle20;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle21;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle22;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle23;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle24;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle25;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle26;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle27;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle28;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle29;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle30;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle4;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle5;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle6;
    private rojerusan.RSPanelsSlider rsmenu;
    private rojerusan.RSPanelsSlider rsminimenu;
    private javax.swing.JTextField txtapellidoE;
    private javax.swing.JTextField txtcargo;
    private javax.swing.JTextField txtdpi;
    private javax.swing.JTextField txtmunicipio;
    private javax.swing.JTextField txtnombreE;
    private javax.swing.JTextField txtpuesto;
    private javax.swing.JTextField txtsueldo;
    private javax.swing.JTextField txttelE;
    private javax.swing.JPanel ventana;
    // End of variables declaration//GEN-END:variables
}
